#include "task/task_list.hpp"
#include "task/task.hpp"
#include "tasks/idle_task.hpp"
#include "tasks/test_task_1.hpp"
#include "tasks/test_task_2.hpp"
#include "tasks/test_task_3.hpp"
#include "tasks/learner_test.hpp"
#include "tasks/external.hpp"
#include "tasks/move_to_joint_pose.hpp"
#include "tasks/move_to_cart_pose.hpp"
#include "tasks/insert_object.hpp"
#include "tasks/extract_object.hpp"
#include "tasks/react_to_event.hpp"
#include "tasks/feature_impedance.hpp"
#include "tasks/feature_collision_detection.hpp"
#include "tasks/feature_force_control.hpp"
#include "tasks/telepresence.hpp"
#include "tasks/place_object.hpp"
#include "tasks/move_trajectory.hpp"
#include "tasks/move_to_location.hpp"
#include "tasks/fetch_object.hpp"
#include "tasks/guiding_mode.hpp"
#include "tasks/handover_object.hpp"
namespace mios{
TaskList::TaskList(){
this->tasks.insert(std::pair<std::string,std::shared_ptr<Task> >("idle_task",std::make_shared<idle_task>()));
this->tasks.insert(std::pair<std::string,std::shared_ptr<Task> >("test_task_1",std::make_shared<test_task_1>()));
this->tasks.insert(std::pair<std::string,std::shared_ptr<Task> >("test_task_2",std::make_shared<test_task_2>()));
this->tasks.insert(std::pair<std::string,std::shared_ptr<Task> >("test_task_3",std::make_shared<test_task_3>()));
this->tasks.insert(std::pair<std::string,std::shared_ptr<Task> >("learner_test",std::make_shared<learner_test>()));
this->tasks.insert(std::pair<std::string,std::shared_ptr<Task> >("external",std::make_shared<external>()));
this->tasks.insert(std::pair<std::string,std::shared_ptr<Task> >("move_to_joint_pose",std::make_shared<move_to_joint_pose>()));
this->tasks.insert(std::pair<std::string,std::shared_ptr<Task> >("move_to_cart_pose",std::make_shared<move_to_cart_pose>()));
this->tasks.insert(std::pair<std::string,std::shared_ptr<Task> >("insert_object",std::make_shared<insert_object>()));
this->tasks.insert(std::pair<std::string,std::shared_ptr<Task> >("extract_object",std::make_shared<extract_object>()));
this->tasks.insert(std::pair<std::string,std::shared_ptr<Task> >("react_to_event",std::make_shared<react_to_event>()));
this->tasks.insert(std::pair<std::string,std::shared_ptr<Task> >("feature_impedance",std::make_shared<feature_impedance>()));
this->tasks.insert(std::pair<std::string,std::shared_ptr<Task> >("feature_collision_detection",std::make_shared<feature_collision_detection>()));
this->tasks.insert(std::pair<std::string,std::shared_ptr<Task> >("feature_force_control",std::make_shared<feature_force_control>()));
this->tasks.insert(std::pair<std::string,std::shared_ptr<Task> >("telepresence",std::make_shared<telepresence>()));
this->tasks.insert(std::pair<std::string,std::shared_ptr<Task> >("place_object",std::make_shared<place_object>()));
this->tasks.insert(std::pair<std::string,std::shared_ptr<Task> >("move_trajectory",std::make_shared<move_trajectory>()));
this->tasks.insert(std::pair<std::string,std::shared_ptr<Task> >("move_to_location",std::make_shared<move_to_location>()));
this->tasks.insert(std::pair<std::string,std::shared_ptr<Task> >("fetch_object",std::make_shared<fetch_object>()));
this->tasks.insert(std::pair<std::string,std::shared_ptr<Task> >("guiding_mode",std::make_shared<guiding_mode>()));
this->tasks.insert(std::pair<std::string,std::shared_ptr<Task> >("handover_object",std::make_shared<handover_object>()));
}
}
