version: "3.8"
services:
  miosL:
    image: "popnut/mios:1.4.0"
    restart: always
    environment:
      - verbosity=info
<<<<<<< HEAD
      - database_port=27017
      - robot_config=0
=======
      - database_port=27005
      - robot_config=1
      - robot_arm=left
>>>>>>> 739ad795c5c2fdb16634c5f1c92ea3b0fa867b98
    network_mode: "host"
    cap_add:
      - SYS_NICE
    depends_on:
      - "ros"
      - "mongo"
  miosR:
    image: "popnut/mios:1.4.0"
    restart: always
    environment:
      - verbosity=info
      - database_port=27005
      - robot_config=1
      - robot_arm=right
    network_mode: "host"
    cap_add:
      - SYS_NICE
    depends_on:
      - "ros"
      - "mongo"      
  ros:
    image: "ros:noetic-ros-core"
    network_mode: "host"
    command: roscore
  mongo:
    image: "mongo:4.4.6"
    ports:
      - "27017:27017"
    volumes:
      - ./localFolder:/data/db

